# Generated by Django 2.0.4 on 2018-04-27 14:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ItemData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField(verbose_name='序号')),
                ('title', models.CharField(max_length=128, verbose_name='名称')),
                ('image', models.FileField(upload_to='item_images/', verbose_name='图片')),
                ('price', models.FloatField(verbose_name='价格')),
                ('location', models.CharField(max_length=32, verbose_name='发货地')),
                ('seller', models.CharField(max_length=32, verbose_name='商家')),
                ('view_sales', models.IntegerField(verbose_name='购买人数')),
            ],
        ),
        migrations.CreateModel(
            name='KeyWord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=32, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='SearchTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site', models.CharField(choices=[('taobao', '淘宝')], max_length=32, verbose_name='网站')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('max_limit', models.IntegerField(default=50, verbose_name='最大抓取个数')),
                ('describe', models.TextField(blank=True, default='', verbose_name='描述')),
                ('keyword', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spider.KeyWord', verbose_name='关键词')),
            ],
        ),
        migrations.AddField(
            model_name='itemdata',
            name='search_task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spider.SearchTask', verbose_name='搜索任务'),
        ),
    ]
