# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-04-22 02:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    # 初始，最初
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ItemData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='', verbose_name='图片')),
                ('price', models.FloatField(verbose_name='价格')),
                ('location', models.FloatField(verbose_name='发货地')),
                ('seller', models.CharField(max_length=32, verbose_name='商家')),
                ('view_sales', models.FloatField(verbose_name='购买人数')),
            ],
        ),
        migrations.CreateModel(
            name='KeyWord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=32, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='SearchTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_created=True, verbose_name='创建时间')),
                ('site', models.CharField(choices=[('taobao', '淘宝')], max_length=32, verbose_name='网站')),
                ('describe', models.TextField(default='')),
                ('keyword', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spider.KeyWord', verbose_name='关键词')),
            ],
        ),
    ]
