# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-04-22 02:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    # 依赖性，相关性
    dependencies = [
        ('spider', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchtask',
            name='max_limit',
            field=models.IntegerField(default=50, verbose_name='最大抓取个数'),
        ),
    ]
