# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-04-22 02:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spider', '0002_searchtask_max_limit'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemdata',
            name='title',
            field=models.CharField(default='', max_length=128, verbose_name='名称'),
            preserve_default=False,
        ),
    ]
