# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-04-22 10:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


# Migration移动
class Migration(migrations.Migration):

    dependencies = [
        ('spider', '0003_itemdata_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemdata',
            name='index',
            field=models.IntegerField(default=0, verbose_name='序号'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='itemdata',
            name='search_task',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='spider.SearchTask', verbose_name='搜索任务'),
            preserve_default=False,
        ),
    ]
