# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-04-22 10:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spider', '0004_auto_20180422_1800'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemdata',
            name='image',
            field=models.FileField(upload_to='item_images/', verbose_name='图片'),
        ),
        migrations.AlterField(
            model_name='itemdata',
            name='location',
            field=models.CharField(max_length=32, verbose_name='发货地'),
        ),
        migrations.AlterField(
            model_name='searchtask',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='searchtask',
            name='describe',
            field=models.TextField(blank=True, default='', verbose_name='描述'),
        ),
    ]
