# Generated by Django 2.0.4 on 2018-04-27 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spider', '0005_auto_20180422_1837'),
    ]

    operations = [
    ]
